// resources/plugins/svelte/components/TheSeoFramework.svelte
<script>
	import { page } from "@inertiajs/svelte";

	let schema = $derived.by(() => {
		const s = $page.props.seo.schema;
		return `&lt;script type="application/ld+json">${JSON.stringify({
			"@context": "https://schema.org",
			"@graph": s,
		})}&lt;/script>`.replaceAll("&lt;", "<");
	});
</script>

<svelte:head>
	<title>{$page.props.seo.title}</title>
	{#each $page.props.seo.links as link}
		<link {...link} />
	{/each}
	{#each $page.props.seo.meta as meta}
		<meta {...meta} />
	{/each}
	{@html schema}
</svelte:head>

// resources/plugins/vue/components/TheSeoFramework.vue
<template>
  <Head :title="seo.title">
    <link v-for="link in seo.links" v-bind="link" />
    <meta v-for="meta in seo.meta" v-bind="meta" />
    <component is="script" type="application/ld+json">
      {{ schema }}
    </component>
  </Head>
</template>

<script setup>
import { computed } from "vue";
import { Head, usePage } from "@inertiajs/vue3";

const seo = computed(() => usePage().props.seo);
const schema = computed(() => {
  return JSON.stringify({
    "@context": "https://schema.org",
    "@graph": seo.value.schema,
  });
});
</script>
